var i18n = $.extend({}, i18n || {}, {
    xgcalendar: {
        dateformat: {
            "fulldaykey": "MMddyyyy",
            "fulldayshow": "L d yyyy",
            "fulldayvalue": "yyyy-MM-dd",
            "Md": "W M/d",
            "Md3": "L d",
            "separator": "-",
            "year_index": 0,
            "month_index":1,
            "day_index": 2,
            "day": "d",
            "sun": "Domingo",
            "mon": "Lunes",
            "tue": "Martes",
            "wed": "Miercoles",
            "thu": "Juves",
            "fri": "Viernes",
            "sat": "Sabado",
            "jan": "Enero",
            "feb": "Febrero",
            "mar": "Marzo",
            "apr": "Abril",
            "may": "Mayo",
            "jun": "Junio",
            "jul": "Julio",
            "aug": "Agosto",
            "sep": "Septiembre",
            "oct": "Octubre",
            "nov": "Noviembre",
            "dec": "Diciembre"
        },
        "no_implemented": "No implementado aun",
        "to_date_view": "Click en la vista de la fecha actual",
        "i_undefined": "Indefinido",
        "allday_event": "Todos los Eventos del Dia",
        "repeat_event": "Repetir Evento",
        "time": "Fecha",
        "event": "Evento",
        "location": "Lugar",
        "participant": "Participantes",
        "get_data_exception": "Excepcion opteniendo datos",
        "new_event": "Nuevo Evento",
        "confirm_delete_event": "Realmente eliminara esta Cita? ",
        "confrim_delete_event_or_all": "Quiere repetir todas las citas o solo esta? \r\nClick [OK] para borrar solo este evento, click [Cancel] borrar todos",
        "data_format_error": "error en el formato de datos! ",
        "invalid_title": "El titulo de la cita no debe estar vacio($<>)",
        "view_no_ready": "La vista no esta Lista",
        "example": "e.j., reunion en AC 107",
        "content": "Cita Con",
        "create_event": "Crear evento",
        "update_detail": "Editar detalles",
        "click_to_detail": "Ver detalles",
        "i_delete": "Borrar",
        "day_plural": "Dias",
        "others": "Otros",
        "item": ""
    }
});


